<a href="https://colab.research.google.com/github/DiFedorchuk/ML_Course/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [10]:
import numpy as np
# Перший спосіб створення вектора
vector = np.random.rand(10)
# Другий спосіб створення вектора
vector1 = np.random.uniform(low= 0.0, high= 1.0, size = 10)
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])

In [29]:
print('Вектор: \n', vector)
print('Матриця: \n',matrix)
print('Розміри матриці: \n',matrix.shape)

Вектор: 
 [0.80783656 0.36003348 0.82134212 0.18913124 0.11786864 0.28916216
 0.66139306 0.79408544 0.72008222 0.39339824]
Матриця: 
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
Розміри матриці: 
 (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [28]:
#1. Додаємо 10 до вектора та округлюємо результат до 2 знаків після коми
vector3 = np.round(vector + 10, 2)
print('vector * 10 :\n',vector3)
# 2. Множення матриці на 2
matrix1 = matrix * 2
print('Матриця помножена на 2 \n',matrix1 )
# 3. Новий вектор який містить квадрат кожного vector
sq_vector = np.square(vector)
print('Вектор який містить квадрат кожного vector \n',sq_vector)

vector * 10 :
 [10.81 10.36 10.82 10.19 10.12 10.29 10.66 10.79 10.72 10.39]
Матриця помножена на 2 
 [[22 28 34]
 [40 46 52]
 [58 64 70]]
Вектор який містить квадрат кожного vector 
 [0.65259991 0.1296241  0.67460287 0.03577062 0.01389302 0.08361476
 0.43744078 0.63057168 0.51851841 0.15476217]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [21]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [34]:
#1. Множення матриць А та В
result_matrix = np.dot(B, A)
print('Результат множення B*А: \n', result_matrix)
#2. Множення result_matrix на вектор С
result_matrix2 = np.dot(result_matrix, C)
print('Результат множення result_matrix*C: \n', result_matrix2)
#3. Множення result_matrix на матрицю D
result_matrix3 = np.dot(result_matrix, D)
print('Результат множення result_matrix*D: \n', result_matrix3)

Результат множення B*А: 
 [[0.7281 0.5202]
 [0.2034 0.2846]]
Результат множення result_matrix*C: 
 [[0.5202]
 [0.2846]]
Результат множення result_matrix*D: 
 [[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [39]:
#1 Транспонування матриці result_matrix
result_matrix_t = result_matrix.T
print('Транспонована матриця result_matrix: \n',result_matrix_t)
#2 Транспонування вектора vector
vector_t = vector.T
print('Транспонований вектор vector: \n',vector_t)
# Так як vector має всього один вимір, то транспонування не змінює результат

Транспонована матриця result_matrix: 
 [[0.7281 0.2034]
 [0.5202 0.2846]]
Транспонований вектор vector: 
 [0.80783656 0.36003348 0.82134212 0.18913124 0.11786864 0.28916216
 0.66139306 0.79408544 0.72008222 0.39339824]


In [38]:
vector

array([0.80783656, 0.36003348, 0.82134212, 0.18913124, 0.11786864,
       0.28916216, 0.66139306, 0.79408544, 0.72008222, 0.39339824])

In [46]:
# 3. numpy.expand_dims над вектором vector
column_vector = np.expand_dims(vector, axis= 1)
print('Перетворюємо vector у стовпчик: \n',column_vector)
# За допомогою даного методу змінили структуру вектора, тепер він має 10 рядків та 1 стовпчик
print('Розмірність  column_vector: \n',column_vector.shape)
# 4. Транспонування column_vector
column_vector_t = column_vector.T
print('Транспонований column_vector: \n',column_vector_t)
print('Розмірність транспонованого column_vector: \n',column_vector_t.shape)
# Транспонування змінило структуру column_vector, тепер він має 1 рядок та 10 стовпчиків

Перетворюємо vector у стовпчик: 
 [[0.80783656]
 [0.36003348]
 [0.82134212]
 [0.18913124]
 [0.11786864]
 [0.28916216]
 [0.66139306]
 [0.79408544]
 [0.72008222]
 [0.39339824]]
Розмірність  column_vector: 
 (10, 1)
Транспонований column_vector: 
 [[0.80783656 0.36003348 0.82134212 0.18913124 0.11786864 0.28916216
  0.66139306 0.79408544 0.72008222 0.39339824]]
Розмірність транспонованого column_vector: 
 (1, 10)
